### ISSUE TITLE
Feature Request : Integrate LETS ENCRYPT in Nginx

### ISSUE THREAD

**Issue by masterpowers** [wmark/docker-wordpress-hhvm#1]
It would be awesome to Have your SSL Certificate be Renew every 3 months
and Run in conjunction with Nginx Thanks ...
Ive Tested it Works Great

**Comment by wmark** [comment]
The ideal *Docker* or *rkt*-based deployment of *Wordpress* and friends is not two, but three containers.

1. One with *MariaDB* (or *MySQL*)
2. … one with PHP or HHVM (this one serves this purpose)
3. … a data container with your *document root*, containing Wordpress; and a directory with certificates.

That way you can update the PHP interpreter (PHP, HHVM) and Wordpress independently from each other.

This image includes (2)+(3) and is meant for the quick CI/CD test of, for example, your plugin or template(s). It's indeed what I use this image for [CDN-Linker](https://github.com/wmark/CDN-Linker).

But I will iterate on the included scripts after lunch and see whether I still like the idea of including **lego** for *Let's Encrypt*.

**Comment by wmark** [comment]
I've decided to not include support for *Let's Encrypt* or others for now. This will be part of the webserver I will eventually move to from *nginx*.

You can still create your own Docker image to override my decision! In case you use the Dockerhub, you can then set a trigger for your Docker image to be rebuild whenever [wmark/wordpress-hhvm](https://hub.docker.com/r/wmark/wordpress-hhvm/) is. (Which in turn gets rebuilt on changes of HHVM, Wordpress, or [blitznote/ubuntu](https://hub.docker.com/r/blitznote/debootstrap-amd64/).)

To get you started:

```Docker
FROM wmark/wordpress-hhvm

# This gets the latest version of 'lego':
RUN mkdir -p /opt/sbin \
 && curl --silent --show-error --fail --location --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" \
      $(curl --silent --show-error --fail --location --header 'Accept: application/json' \
        https://api.github.com/repos/xenolf/lego/releases/latest \
        | jq -r '.assets[] | select(.name | contains("linux_amd64")) | select(.browser_download_url | contains(".tar")) | .browser_download_url') \
    | tar --no-same-owner --strip-components=1 -C /opt/sbin -xz "lego/lego"

# Add a line to /etc/fcrontab, like: %nightly root /opt/sbin/lego … run
# Add a line to nginx/vhosts.d/* with `location /.well-known/acme-challenge/ { root …; }` for the challenge.
```
